// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartFleetBE.Model;

#nullable disable

namespace SmartFleetBE.Migrations
{
    [DbContext(typeof(SmartFleetDbContext))]
    [Migration("20260917060415_fix")]
    partial class fix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartFleetBE.DeliveryVerification", b =>
                {
                    b.Property<long>("VerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("VerificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VerificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("ExpectedQrPayload")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<long>("MissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("MissionID");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("QrPayloadScanned")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("VerificationStage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("VerificationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("QRCODE");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("VerifiedBy")
                        .HasColumnType("int");

                    b.HasKey("VerificationId")
                        .HasName("PK__Delivery__306D4927F910F468");

                    b.HasIndex("VerifiedBy");

                    b.HasIndex(new[] { "MissionId", "VerificationStage" }, "UQ_DeliveryVerifications_Mission_Stage")
                        .IsUnique();

                    b.ToTable("DeliveryVerifications");
                });

            modelBuilder.Entity("SmartFleetBE.MapConfiguration", b =>
                {
                    b.Property<int>("MapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MapID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MapId"));

                    b.Property<string>("CoordinateSystem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("LOCAL_METRIC");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("ImageHeightPixels")
                        .HasColumnType("int");

                    b.Property<int?>("ImageWidthPixels")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MapImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MapImageURL");

                    b.Property<string>("MapMetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MapName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("MapSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("LIDAR_SLAM");

                    b.Property<string>("MapVersion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("OriginX")
                        .HasColumnType("decimal(12, 4)");

                    b.Property<decimal>("OriginY")
                        .HasColumnType("decimal(12, 4)");

                    b.Property<decimal>("OriginYaw")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<decimal>("ResolutionMeterPerPixel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 6)")
                        .HasDefaultValue(0.050000m);

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("WarehouseID");

                    b.HasKey("MapId")
                        .HasName("PK__MapConfi__3265E2FBA5C273BF");

                    b.HasIndex(new[] { "WarehouseId", "MapVersion" }, "UQ_MapConfigurations_Warehouse_Version")
                        .IsUnique();

                    b.HasIndex(new[] { "WarehouseId" }, "UX_MapConfigurations_OneActivePerWarehouse")
                        .IsUnique()
                        .HasFilter("([IsActive]=(1))");

                    b.ToTable("MapConfigurations");
                });

            modelBuilder.Entity("SmartFleetBE.Mission", b =>
                {
                    b.Property<long>("MissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MissionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MissionId"));

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("AssignmentID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("EndExecutionTime")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LastProgressAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("MissionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MissionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasDefaultValue("INITIALIZING");

                    b.Property<DateTime?>("StartExecutionTime")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal>("TotalDistanceMeters")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("TotalDurationSeconds")
                        .HasColumnType("int");

                    b.HasKey("MissionId")
                        .HasName("PK__Missions__66DFB85463EEA7CC");

                    b.HasIndex(new[] { "MissionStatus", "LastProgressAt" }, "IX_Missions_Status_Progress");

                    b.HasIndex(new[] { "AssignmentId" }, "UQ__Missions__32499E56B445480D")
                        .IsUnique();

                    b.HasIndex(new[] { "MissionCode" }, "UQ__Missions__B986D1CA64921B15")
                        .IsUnique();

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("SmartFleetBE.MissionStatusHistory", b =>
                {
                    b.Property<long>("MissionStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MissionStatusHistoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MissionStatusHistoryId"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("ChangedBy")
                        .HasColumnType("int");

                    b.Property<long>("MissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("MissionID");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("SYSTEM");

                    b.HasKey("MissionStatusHistoryId")
                        .HasName("PK__MissionS__7736D18832D593F8");

                    b.HasIndex("ChangedBy");

                    b.HasIndex(new[] { "MissionId", "ChangedAt" }, "IX_MissionStatusHistories_Mission_Time")
                        .IsDescending(false, true);

                    b.ToTable("MissionStatusHistories");
                });

            modelBuilder.Entity("SmartFleetBE.MissionWaypoint", b =>
                {
                    b.Property<long>("WaypointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("WaypointID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WaypointId"));

                    b.Property<decimal>("CoordX")
                        .HasColumnType("decimal(12, 4)");

                    b.Property<decimal>("CoordY")
                        .HasColumnType("decimal(12, 4)");

                    b.Property<bool>("IsReached")
                        .HasColumnType("bit");

                    b.Property<long>("MissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("MissionID");

                    b.Property<DateTime?>("ReachedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<int?>("StationId")
                        .HasColumnType("int")
                        .HasColumnName("StationID");

                    b.Property<string>("WaypointAction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("PASS_THROUGH");

                    b.Property<decimal>("YawAngle")
                        .HasColumnType("decimal(10, 6)");

                    b.HasKey("WaypointId")
                        .HasName("PK__MissionW__DF81B324B1BD14F2");

                    b.HasIndex("StationId");

                    b.HasIndex(new[] { "MissionId", "SequenceNumber" }, "IX_MissionWaypoints_Mission_Sequence");

                    b.HasIndex(new[] { "MissionId", "SequenceNumber" }, "UQ_MissionWaypoints_Mission_Sequence")
                        .IsUnique();

                    b.ToTable("MissionWaypoints");
                });

            modelBuilder.Entity("SmartFleetBE.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("NotificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsBroadcast")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationCategory")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<long?>("RelatedIncidentId")
                        .HasColumnType("bigint")
                        .HasColumnName("RelatedIncidentID");

                    b.Property<long?>("RelatedMissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("RelatedMissionID");

                    b.Property<int?>("RelatedRobotId")
                        .HasColumnType("int")
                        .HasColumnName("RelatedRobotID");

                    b.Property<long?>("RelatedTaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("RelatedTaskID");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("INFO");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E321F842579");

                    b.HasIndex("RelatedIncidentId");

                    b.HasIndex("RelatedMissionId");

                    b.HasIndex("RelatedRobotId");

                    b.HasIndex("RelatedTaskId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SmartFleetBE.NotificationRecipient", b =>
                {
                    b.Property<long>("NotificationId")
                        .HasColumnType("bigint")
                        .HasColumnName("NotificationID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReadAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.HasKey("NotificationId", "UserId");

                    b.HasIndex(new[] { "UserId", "IsRead" }, "IX_NotificationRecipients_User_Read");

                    b.ToTable("NotificationRecipients");
                });

            modelBuilder.Entity("SmartFleetBE.RefreshToken", b =>
                {
                    b.Property<long>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("RefreshTokenID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RefreshTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("RefreshTokenId")
                        .HasName("PK__RefreshT__F5845E5950D3F69E");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "TokenHash" }, "UQ__RefreshT__BCB33F92D92D7453")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SmartFleetBE.Robot", b =>
                {
                    b.Property<int>("RobotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RobotID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RobotId"));

                    b.Property<decimal?>("BatteryPercent")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("BatteryVoltage")
                        .HasColumnType("decimal(6, 3)");

                    b.Property<string>("ConnectionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("OFFLINE");

                    b.Property<string>("ControlSoftware")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasDefaultValue("NVIDIA_JETRACER_PYTHON");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<decimal?>("CurrentCoordX")
                        .HasColumnType("decimal(12, 4)");

                    b.Property<decimal?>("CurrentCoordY")
                        .HasColumnType("decimal(12, 4)");

                    b.Property<decimal?>("CurrentHeading")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastHeartbeatTime")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("LastTelemetryTime")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(17)
                        .IsUnicode(false)
                        .HasColumnType("varchar(17)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasDefaultValue("JetRacer");

                    b.Property<string>("MqttClientIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("OperationalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("AVAILABLE");

                    b.Property<string>("RobotAgentVersion")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("RobotCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("RobotType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("PHYSICAL");

                    b.Property<int>("TotalOperatingMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("WarehouseID");

                    b.HasKey("RobotId")
                        .HasName("PK__Robots__FBB332A1B584813A");

                    b.HasIndex(new[] { "WarehouseId", "ConnectionStatus", "OperationalStatus", "BatteryPercent" }, "IX_Robots_DispatchCandidate");

                    b.HasIndex(new[] { "MqttClientIdentifier" }, "UQ__Robots__558F275E0A2C002B")
                        .IsUnique();

                    b.HasIndex(new[] { "RobotCode" }, "UQ__Robots__F9DB9D4E7380E1A3")
                        .IsUnique();

                    b.ToTable("Robots");
                });

            modelBuilder.Entity("SmartFleetBE.RobotIncident", b =>
                {
                    b.Property<long>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IncidentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IncidentId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<long?>("MissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("MissionID");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("ResolvedBy")
                        .HasColumnType("int");

                    b.Property<int>("RobotId")
                        .HasColumnType("int")
                        .HasColumnName("RobotID");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("WARNING");

                    b.Property<long?>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("TaskID");

                    b.HasKey("IncidentId")
                        .HasName("PK__RobotInc__3D8053925C3BBF17");

                    b.HasIndex("MissionId");

                    b.HasIndex("ResolvedBy");

                    b.HasIndex("RobotId");

                    b.HasIndex("TaskId");

                    b.HasIndex(new[] { "IsResolved", "Severity", "CreatedAt" }, "IX_RobotIncidents_Open")
                        .IsDescending(false, false, true);

                    b.ToTable("RobotIncidents");
                });

            modelBuilder.Entity("SmartFleetBE.RobotMaintenanceRecord", b =>
                {
                    b.Property<long>("MaintenanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MaintenanceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaintenanceId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("CompletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MaintenanceStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("SCHEDULED");

                    b.Property<string>("MaintenanceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("RobotId")
                        .HasColumnType("int")
                        .HasColumnName("RobotID");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("StartedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.HasKey("MaintenanceId")
                        .HasName("PK__RobotMai__E60542B564C218A4");

                    b.HasIndex("CompletedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "RobotId", "MaintenanceStatus", "CreatedAt" }, "IX_RobotMaintenance_Robot_Status")
                        .IsDescending(false, false, true);

                    b.ToTable("RobotMaintenanceRecords");
                });

            modelBuilder.Entity("SmartFleetBE.RobotStatusHistory", b =>
                {
                    b.Property<long>("RobotStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("RobotStatusHistoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RobotStatusHistoryId"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("NewConnectionStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NewOperationalStatus")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PreviousConnectionStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PreviousOperationalStatus")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RobotId")
                        .HasColumnType("int")
                        .HasColumnName("RobotID");

                    b.HasKey("RobotStatusHistoryId")
                        .HasName("PK__RobotSta__DE50B2D89DEB2C77");

                    b.HasIndex(new[] { "RobotId", "ChangedAt" }, "IX_RobotStatusHistories_Robot_Time")
                        .IsDescending(false, true);

                    b.ToTable("RobotStatusHistories");
                });

            modelBuilder.Entity("SmartFleetBE.RobotTelemetryLog", b =>
                {
                    b.Property<long>("TelemetryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TelemetryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TelemetryId"));

                    b.Property<decimal?>("AngularVelocity")
                        .HasColumnType("decimal(8, 3)");

                    b.Property<decimal?>("BatteryCurrentMa")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("BatteryPercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("BatteryPowerMw")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal?>("BatteryVoltage")
                        .HasColumnType("decimal(6, 3)");

                    b.Property<decimal?>("CpuTemperature")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<decimal?>("Heading")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<decimal?>("LinearVelocity")
                        .HasColumnType("decimal(8, 3)");

                    b.Property<decimal?>("PositionX")
                        .HasColumnType("decimal(12, 4)");

                    b.Property<decimal?>("PositionY")
                        .HasColumnType("decimal(12, 4)");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("RobotId")
                        .HasColumnType("int")
                        .HasColumnName("RobotID");

                    b.Property<decimal?>("WifiSignalDbm")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("TelemetryId")
                        .HasName("PK__RobotTel__157CAF178D087245");

                    b.HasIndex(new[] { "RobotId", "RecordedAt" }, "IX_RobotTelemetry_Robot_Time")
                        .IsDescending(false, true);

                    b.ToTable("RobotTelemetryLogs");
                });

            modelBuilder.Entity("SmartFleetBE.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3A6F72D3EF");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B6160F78CB88D")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SmartFleetBE.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationId"));

                    b.Property<decimal>("CoordX")
                        .HasColumnType("decimal(12, 4)");

                    b.Property<decimal>("CoordY")
                        .HasColumnType("decimal(12, 4)");

                    b.Property<decimal>("CoordZ")
                        .HasColumnType("decimal(12, 4)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<string>("QrCodePayload")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("StationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal>("YawAngle")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int")
                        .HasColumnName("ZoneID");

                    b.HasKey("StationId")
                        .HasName("PK__Stations__E0D8A6DD087AA7E7");

                    b.HasIndex("ZoneId");

                    b.HasIndex(new[] { "StationCode" }, "UQ__Stations__D3885618FF7AF6E8")
                        .IsUnique();

                    b.HasIndex(new[] { "QrCodePayload" }, "UX_Stations_QrCodePayload")
                        .IsUnique()
                        .HasFilter("([QrCodePayload] IS NOT NULL)");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("SmartFleetBE.SystemAuditLog", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("AuditID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditId"));

                    b.Property<string>("ActionCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EntityID");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("AuditId")
                        .HasName("PK__SystemAu__A17F23B8AA02DA70");

                    b.HasIndex("UserId");

                    b.ToTable("SystemAuditLogs");
                });

            modelBuilder.Entity("SmartFleetBE.TaskAssignment", b =>
                {
                    b.Property<long>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("AssignmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AssignmentId"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("AssignedBy")
                        .HasColumnType("int");

                    b.Property<string>("AssignmentReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AssignmentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("ACTIVE");

                    b.Property<string>("AssignmentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("AUTO");

                    b.Property<decimal?>("BatteryPercentAtAssignment")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("CandidateDistanceMeters")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal?>("DispatchScore")
                        .HasColumnType("decimal(14, 4)");

                    b.Property<DateTime?>("EndedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ReassignmentReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RobotId")
                        .HasColumnType("int")
                        .HasColumnName("RobotID");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("TaskID");

                    b.Property<int?>("WorkloadAtAssignment")
                        .HasColumnType("int");

                    b.HasKey("AssignmentId")
                        .HasName("PK__TaskAssi__32499E579FA23A81");

                    b.HasIndex("AssignedBy");

                    b.HasIndex(new[] { "RobotId", "AssignmentStatus", "AssignedAt" }, "IX_TaskAssignments_Robot_Status")
                        .IsDescending(false, false, true);

                    b.HasIndex(new[] { "RobotId" }, "UX_TaskAssignments_OneActivePerRobot")
                        .IsUnique()
                        .HasFilter("([AssignmentStatus]='ACTIVE')");

                    b.HasIndex(new[] { "TaskId" }, "UX_TaskAssignments_OneActivePerTask")
                        .IsUnique()
                        .HasFilter("([AssignmentStatus]='ACTIVE')");

                    b.ToTable("TaskAssignments");
                });

            modelBuilder.Entity("SmartFleetBE.TaskStatusHistory", b =>
                {
                    b.Property<long>("TaskStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TaskStatusHistoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TaskStatusHistoryId"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("ChangedBy")
                        .HasColumnType("int");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("TaskID");

                    b.HasKey("TaskStatusHistoryId")
                        .HasName("PK__TaskStat__AAC202A6D1D8F8AC");

                    b.HasIndex("ChangedBy");

                    b.HasIndex(new[] { "TaskId", "ChangedAt" }, "IX_TaskStatusHistories_Task_Time")
                        .IsDescending(false, true);

                    b.ToTable("TaskStatusHistories");
                });

            modelBuilder.Entity("SmartFleetBE.TransportTask", b =>
                {
                    b.Property<long>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TaskID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TaskId"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryStationId")
                        .HasColumnType("int")
                        .HasColumnName("DeliveryStationID");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ItemDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PackageCode")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<decimal?>("PayloadWeightKg")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int>("PickupStationId")
                        .HasColumnType("int")
                        .HasColumnName("PickupStationID");

                    b.Property<int>("PriorityLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<DateTime?>("QueuedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("ScheduledTime")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("StartedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("TaskStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("PENDING");

                    b.Property<string>("TaskTrackingCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("WarehouseID");

                    b.HasKey("TaskId")
                        .HasName("PK__Transpor__7C6949D1AC49FF2D");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeliveryStationId");

                    b.HasIndex("PickupStationId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex(new[] { "TaskStatus", "PriorityLevel", "CreatedAt" }, "IX_TransportTasks_Status_Priority")
                        .IsDescending(false, true, false);

                    b.HasIndex(new[] { "TaskTrackingCode" }, "UQ__Transpor__3AE3883397055726")
                        .IsUnique();

                    b.ToTable("TransportTasks");
                });

            modelBuilder.Entity("SmartFleetBE.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCACCEA03989");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E44BB02AEF")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105342ED34DCC")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartFleetBE.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("SmartFleetBE.Warehouse", b =>
                {
                    b.Property<int>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WarehouseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarehouseId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("WarehouseId")
                        .HasName("PK__Warehous__2608AFD923AF8508");

                    b.HasIndex(new[] { "WarehouseCode" }, "UQ__Warehous__1686A0569815041D")
                        .IsUnique();

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("SmartFleetBE.Zone", b =>
                {
                    b.Property<int>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ZoneID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZoneId"));

                    b.Property<string>("BoundaryJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("SpeedLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(0.50m);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("WarehouseID");

                    b.Property<string>("ZoneCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ZoneType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("ZoneId")
                        .HasName("PK__Zones__601667952B02B43F");

                    b.HasIndex(new[] { "WarehouseId", "ZoneCode" }, "UQ_Zones_Warehouse_Code")
                        .IsUnique();

                    b.HasIndex(new[] { "WarehouseId", "ZoneName" }, "UQ_Zones_Warehouse_Name")
                        .IsUnique();

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("SmartFleetBE.DeliveryVerification", b =>
                {
                    b.HasOne("SmartFleetBE.Mission", "Mission")
                        .WithMany("DeliveryVerifications")
                        .HasForeignKey("MissionId")
                        .IsRequired()
                        .HasConstraintName("FK_DeliveryVerifications_Missions");

                    b.HasOne("SmartFleetBE.User", "VerifiedByNavigation")
                        .WithMany("DeliveryVerifications")
                        .HasForeignKey("VerifiedBy")
                        .HasConstraintName("FK_DeliveryVerifications_Users");

                    b.Navigation("Mission");

                    b.Navigation("VerifiedByNavigation");
                });

            modelBuilder.Entity("SmartFleetBE.MapConfiguration", b =>
                {
                    b.HasOne("SmartFleetBE.Warehouse", "Warehouse")
                        .WithOne("MapConfiguration")
                        .HasForeignKey("SmartFleetBE.MapConfiguration", "WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_MapConfigurations_Warehouses");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("SmartFleetBE.Mission", b =>
                {
                    b.HasOne("SmartFleetBE.TaskAssignment", "Assignment")
                        .WithOne("Mission")
                        .HasForeignKey("SmartFleetBE.Mission", "AssignmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Missions_TaskAssignments");

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("SmartFleetBE.MissionStatusHistory", b =>
                {
                    b.HasOne("SmartFleetBE.User", "ChangedByNavigation")
                        .WithMany("MissionStatusHistories")
                        .HasForeignKey("ChangedBy")
                        .HasConstraintName("FK_MissionStatusHistories_Users");

                    b.HasOne("SmartFleetBE.Mission", "Mission")
                        .WithMany("MissionStatusHistories")
                        .HasForeignKey("MissionId")
                        .IsRequired()
                        .HasConstraintName("FK_MissionStatusHistories_Missions");

                    b.Navigation("ChangedByNavigation");

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("SmartFleetBE.MissionWaypoint", b =>
                {
                    b.HasOne("SmartFleetBE.Mission", "Mission")
                        .WithMany("MissionWaypoints")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MissionWaypoints_Missions");

                    b.HasOne("SmartFleetBE.Station", "Station")
                        .WithMany("MissionWaypoints")
                        .HasForeignKey("StationId")
                        .HasConstraintName("FK_MissionWaypoints_Stations");

                    b.Navigation("Mission");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("SmartFleetBE.Notification", b =>
                {
                    b.HasOne("SmartFleetBE.RobotIncident", "RelatedIncident")
                        .WithMany("Notifications")
                        .HasForeignKey("RelatedIncidentId")
                        .HasConstraintName("FK_Notifications_Incidents");

                    b.HasOne("SmartFleetBE.Mission", "RelatedMission")
                        .WithMany("Notifications")
                        .HasForeignKey("RelatedMissionId")
                        .HasConstraintName("FK_Notifications_Missions");

                    b.HasOne("SmartFleetBE.Robot", "RelatedRobot")
                        .WithMany("Notifications")
                        .HasForeignKey("RelatedRobotId")
                        .HasConstraintName("FK_Notifications_Robots");

                    b.HasOne("SmartFleetBE.TransportTask", "RelatedTask")
                        .WithMany("Notifications")
                        .HasForeignKey("RelatedTaskId")
                        .HasConstraintName("FK_Notifications_Tasks");

                    b.Navigation("RelatedIncident");

                    b.Navigation("RelatedMission");

                    b.Navigation("RelatedRobot");

                    b.Navigation("RelatedTask");
                });

            modelBuilder.Entity("SmartFleetBE.NotificationRecipient", b =>
                {
                    b.HasOne("SmartFleetBE.Notification", "Notification")
                        .WithMany("NotificationRecipients")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NotificationRecipients_Notifications");

                    b.HasOne("SmartFleetBE.User", "User")
                        .WithMany("NotificationRecipients")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_NotificationRecipients_Users");

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartFleetBE.RefreshToken", b =>
                {
                    b.HasOne("SmartFleetBE.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartFleetBE.Robot", b =>
                {
                    b.HasOne("SmartFleetBE.Warehouse", "Warehouse")
                        .WithMany("Robots")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_Robots_Warehouses");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("SmartFleetBE.RobotIncident", b =>
                {
                    b.HasOne("SmartFleetBE.Mission", "Mission")
                        .WithMany("RobotIncidents")
                        .HasForeignKey("MissionId")
                        .HasConstraintName("FK_RobotIncidents_Missions");

                    b.HasOne("SmartFleetBE.User", "ResolvedByNavigation")
                        .WithMany("RobotIncidents")
                        .HasForeignKey("ResolvedBy")
                        .HasConstraintName("FK_RobotIncidents_ResolvedBy");

                    b.HasOne("SmartFleetBE.Robot", "Robot")
                        .WithMany("RobotIncidents")
                        .HasForeignKey("RobotId")
                        .IsRequired()
                        .HasConstraintName("FK_RobotIncidents_Robots");

                    b.HasOne("SmartFleetBE.TransportTask", "Task")
                        .WithMany("RobotIncidents")
                        .HasForeignKey("TaskId")
                        .HasConstraintName("FK_RobotIncidents_Tasks");

                    b.Navigation("Mission");

                    b.Navigation("ResolvedByNavigation");

                    b.Navigation("Robot");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("SmartFleetBE.RobotMaintenanceRecord", b =>
                {
                    b.HasOne("SmartFleetBE.User", "CompletedByNavigation")
                        .WithMany("RobotMaintenanceRecordCompletedByNavigations")
                        .HasForeignKey("CompletedBy")
                        .HasConstraintName("FK_RobotMaintenanceRecords_CompletedBy");

                    b.HasOne("SmartFleetBE.User", "CreatedByNavigation")
                        .WithMany("RobotMaintenanceRecordCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_RobotMaintenanceRecords_CreatedBy");

                    b.HasOne("SmartFleetBE.Robot", "Robot")
                        .WithMany("RobotMaintenanceRecords")
                        .HasForeignKey("RobotId")
                        .IsRequired()
                        .HasConstraintName("FK_RobotMaintenanceRecords_Robots");

                    b.Navigation("CompletedByNavigation");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("SmartFleetBE.RobotStatusHistory", b =>
                {
                    b.HasOne("SmartFleetBE.Robot", "Robot")
                        .WithMany("RobotStatusHistories")
                        .HasForeignKey("RobotId")
                        .IsRequired()
                        .HasConstraintName("FK_RobotStatusHistories_Robots");

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("SmartFleetBE.RobotTelemetryLog", b =>
                {
                    b.HasOne("SmartFleetBE.Robot", "Robot")
                        .WithMany("RobotTelemetryLogs")
                        .HasForeignKey("RobotId")
                        .IsRequired()
                        .HasConstraintName("FK_RobotTelemetryLogs_Robots");

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("SmartFleetBE.Station", b =>
                {
                    b.HasOne("SmartFleetBE.Zone", "Zone")
                        .WithMany("Stations")
                        .HasForeignKey("ZoneId")
                        .IsRequired()
                        .HasConstraintName("FK_Stations_Zones");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("SmartFleetBE.SystemAuditLog", b =>
                {
                    b.HasOne("SmartFleetBE.User", "User")
                        .WithMany("SystemAuditLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_SystemAuditLogs_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartFleetBE.TaskAssignment", b =>
                {
                    b.HasOne("SmartFleetBE.User", "AssignedByNavigation")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("AssignedBy")
                        .HasConstraintName("FK_TaskAssignments_Users");

                    b.HasOne("SmartFleetBE.Robot", "Robot")
                        .WithOne("TaskAssignment")
                        .HasForeignKey("SmartFleetBE.TaskAssignment", "RobotId")
                        .IsRequired()
                        .HasConstraintName("FK_TaskAssignments_Robots");

                    b.HasOne("SmartFleetBE.TransportTask", "Task")
                        .WithOne("TaskAssignment")
                        .HasForeignKey("SmartFleetBE.TaskAssignment", "TaskId")
                        .IsRequired()
                        .HasConstraintName("FK_TaskAssignments_Tasks");

                    b.Navigation("AssignedByNavigation");

                    b.Navigation("Robot");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("SmartFleetBE.TaskStatusHistory", b =>
                {
                    b.HasOne("SmartFleetBE.User", "ChangedByNavigation")
                        .WithMany("TaskStatusHistories")
                        .HasForeignKey("ChangedBy")
                        .HasConstraintName("FK_TaskStatusHistories_Users");

                    b.HasOne("SmartFleetBE.TransportTask", "Task")
                        .WithMany("TaskStatusHistories")
                        .HasForeignKey("TaskId")
                        .IsRequired()
                        .HasConstraintName("FK_TaskStatusHistories_Tasks");

                    b.Navigation("ChangedByNavigation");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("SmartFleetBE.TransportTask", b =>
                {
                    b.HasOne("SmartFleetBE.User", "CreatedByNavigation")
                        .WithMany("TransportTasks")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_TransportTasks_CreatedBy");

                    b.HasOne("SmartFleetBE.Station", "DeliveryStation")
                        .WithMany("TransportTaskDeliveryStations")
                        .HasForeignKey("DeliveryStationId")
                        .IsRequired()
                        .HasConstraintName("FK_TransportTasks_DeliveryStation");

                    b.HasOne("SmartFleetBE.Station", "PickupStation")
                        .WithMany("TransportTaskPickupStations")
                        .HasForeignKey("PickupStationId")
                        .IsRequired()
                        .HasConstraintName("FK_TransportTasks_PickupStation");

                    b.HasOne("SmartFleetBE.Warehouse", "Warehouse")
                        .WithMany("TransportTasks")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_TransportTasks_Warehouses");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("DeliveryStation");

                    b.Navigation("PickupStation");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("SmartFleetBE.UserRole", b =>
                {
                    b.HasOne("SmartFleetBE.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Roles");

                    b.HasOne("SmartFleetBE.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Users");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartFleetBE.Zone", b =>
                {
                    b.HasOne("SmartFleetBE.Warehouse", "Warehouse")
                        .WithMany("Zones")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK_Zones_Warehouses");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("SmartFleetBE.Mission", b =>
                {
                    b.Navigation("DeliveryVerifications");

                    b.Navigation("MissionStatusHistories");

                    b.Navigation("MissionWaypoints");

                    b.Navigation("Notifications");

                    b.Navigation("RobotIncidents");
                });

            modelBuilder.Entity("SmartFleetBE.Notification", b =>
                {
                    b.Navigation("NotificationRecipients");
                });

            modelBuilder.Entity("SmartFleetBE.Robot", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("RobotIncidents");

                    b.Navigation("RobotMaintenanceRecords");

                    b.Navigation("RobotStatusHistories");

                    b.Navigation("RobotTelemetryLogs");

                    b.Navigation("TaskAssignment");
                });

            modelBuilder.Entity("SmartFleetBE.RobotIncident", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("SmartFleetBE.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SmartFleetBE.Station", b =>
                {
                    b.Navigation("MissionWaypoints");

                    b.Navigation("TransportTaskDeliveryStations");

                    b.Navigation("TransportTaskPickupStations");
                });

            modelBuilder.Entity("SmartFleetBE.TaskAssignment", b =>
                {
                    b.Navigation("Mission");
                });

            modelBuilder.Entity("SmartFleetBE.TransportTask", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("RobotIncidents");

                    b.Navigation("TaskAssignment");

                    b.Navigation("TaskStatusHistories");
                });

            modelBuilder.Entity("SmartFleetBE.User", b =>
                {
                    b.Navigation("DeliveryVerifications");

                    b.Navigation("MissionStatusHistories");

                    b.Navigation("NotificationRecipients");

                    b.Navigation("RefreshTokens");

                    b.Navigation("RobotIncidents");

                    b.Navigation("RobotMaintenanceRecordCompletedByNavigations");

                    b.Navigation("RobotMaintenanceRecordCreatedByNavigations");

                    b.Navigation("SystemAuditLogs");

                    b.Navigation("TaskAssignments");

                    b.Navigation("TaskStatusHistories");

                    b.Navigation("TransportTasks");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SmartFleetBE.Warehouse", b =>
                {
                    b.Navigation("MapConfiguration");

                    b.Navigation("Robots");

                    b.Navigation("TransportTasks");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("SmartFleetBE.Zone", b =>
                {
                    b.Navigation("Stations");
                });
#pragma warning restore 612, 618
        }
    }
}
